# Generated by Django 4.1.4 on 2023-05-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile_isim_profile_soyisim'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnlasmaModeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_adi', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'AnlasmaModeli',
                'verbose_name_plural': 'AnlasmaModelleri',
            },
        ),
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=11)),
                ('marka', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('sigorta_no', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Arac',
                'verbose_name_plural': 'Araclar',
            },
        ),
        migrations.CreateModel(
            name='Araci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calistigi_sirket', models.CharField(blank=True, max_length=50, null=True)),
                ('kimlik_no', models.CharField(blank=True, max_length=11, null=True)),
                ('isim', models.CharField(max_length=25)),
                ('soyisim', models.CharField(max_length=25)),
                ('iban', models.CharField(blank=True, max_length=26, null=True)),
                ('telefon', models.BigIntegerField()),
                ('email', models.CharField(blank=True, max_length=25, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Araci',
                'verbose_name_plural': 'Aracilar',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=25)),
                ('soyisim', models.CharField(max_length=25)),
                ('iban', models.CharField(blank=True, max_length=26, null=True)),
                ('telefon', models.BigIntegerField()),
                ('email', models.CharField(blank=True, max_length=25, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Expertler',
            },
        ),
        migrations.CreateModel(
            name='Sigorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=25)),
                ('adres', models.CharField(blank=True, max_length=100, null=True)),
                ('telefon', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Sigorta',
                'verbose_name_plural': 'Sigortalar',
            },
        ),
        migrations.CreateModel(
            name='KazaKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaza_tarihi', models.DateField(blank=True, null=True)),
                ('asama', models.CharField(blank=True, choices=[('1', 'Sigorta Şirketinden Değer Kaybı Talebi '), ('2', 'Tahkim Komisyonunda Ön İnceleme'), ('3', 'Tahkim Komisyon Heyetince İnceleme'), ('4', 'Tutarın Sigorta Şirketince Ödenmesi'), ('5', 'Süreç Tamamlandı')], max_length=1, null=True)),
                ('asama_tarihi', models.DateField()),
                ('tahmini_deger_kaybi', models.PositiveIntegerField(blank=True, null=True)),
                ('anlasma_modeli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.anlasmamodeli')),
                ('arac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.arac')),
                ('araci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.araci')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expert')),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('sigorta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sigorta')),
            ],
            options={
                'verbose_name': 'KazaKaydi',
                'verbose_name_plural': 'KazaKayıtları',
            },
        ),
        migrations.AddField(
            model_name='arac',
            name='sigorta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sigorta'),
        ),
    ]
