# Generated by Django 4.1.4 on 2023-05-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_arac_yil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='araci',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sigorta',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
