# Generated by Django 4.1.4 on 2023-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_araci_email_alter_expert_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kazakaydi',
            name='gerceklesen_deger_kaybi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
