# Generated by Django 4.1.4 on 2023-05-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isim',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='soyisim',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
